### ISSUE TITLE
Discord invite link expired

### ISSUE THREAD

**Issue by NiklasDanz** [exelotl/natu#2]
Hey, first of all thanks for the great library!
I have a question I'd like to ask you, but the discord link in the readme expired. Could you please share a new one (without an expiration time)?

**Comment by IamRifki** [comment]
Currently, the server is restricted due to spambots invading it. I could email you an invite link, however.

**Comment by NiklasDanz** [comment]
Thanks. That'd be nice. _meindigitalesich AT gmail.com_

**Comment by NiklasDanz** [comment]
I sent you an email

**Comment by IamRifki** [comment]
Sent!

**Comment by exelotl** [comment]
Thanks for the help Dania :+1:
I'll update the readme with a link to the bridged IRC channel for the time being

**Comment by IamRifki** [comment]
@exelotl Should we link to the GBADev Discord instead?

**Comment by IamRifki** [comment]
@exelotl Should we close this issue?

**Comment by exelotl** [comment]
Yep, thanks a bunch! Maybe I'll make the link more prominent after the official server announcement 👍
